# Generated by Django 2.2.4 on 2019-10-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_yourself', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqs',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
