# Generated by Django 2.2.4 on 2019-11-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_yourself', '0004_auto_20191102_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catagory_explanation',
            field=models.TextField(blank=True, help_text='Explanation to be shown For the Catagory ', max_length=2000, verbose_name='Catagory Explanation'),
        ),
    ]
