# Generated by Django 2.2.4 on 2019-11-11 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_yourself', '0005_category_catagory_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat',
            name='catag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_yourself.Category', verbose_name='Catagory'),
        ),
    ]
